detect_ball:
  ros__parameters:
    websocket_url: "ws://172.20.10.3:8765"

detect_ball_3d:
  ros__parameters:
    h_fov: 1.089
    ball_radius: 0.033
    camera_frame: "camera_link_optical"

follow_ball_action_server:
  ros__parameters:
    rcv_timeout_secs: 2.0
    angular_chase_multiplier: 0.6
    forward_chase_speed: 0.5
    min_forward_chase_speed: 0.25
    search_angular_speed: 2.0
    min_angular_speed: 1.5
    max_size_thresh: 0.4
    filter_value: 0.7
    forward_distance: 1.0
    creep_speed: 0.6

deposit_to_box_action_server:
  ros__parameters:
    centroid_threshold: 0.2
    alignment_threshold: 0.25
    backup_time: 15.0
    forward_speed: 0.3
    turn_speed: 1.4
    search_turn_speed: 2.0
    backup_speed: -0.3

follow_ball:
  ros__parameters:
    rcv_timeout_secs: 2.0
    angular_chase_multiplier: 1.2
    forward_chase_speed: 0.8
    search_angular_speed: 1.4
    min_angular_speed: 1.2
    max_size_thresh: 0.07
    filter_value: 0.1
    forward_distance: 1.0
