# FollowBall.action
# The goal definition
# In this case, there is no specific goal input required,
# but you might want to leave an option for a timeout or other parameters.
# Optional timeout in seconds, can be set to 0 if not needed
float32 timeout
---
# The result definition
# Result indicates whether the goal was successfully completed
bool success
---
# The feedback definition
# Feedback will include the current distance to the ball
string current_state
